name: mongo-sharding

services:
  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv
    command: mongod --port 27017 --configsvr --replSet config_replica_set
    volumes:
      - config_data:/data/configdb

  shard1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1
    command: mongod --port 27018 --shardsvr --replSet shard1
    volumes:
      - shard1_data:/data/db
    ports:
      - "27018:27018"

  shard2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2
    command: mongod --port 27019 --shardsvr --replSet shard2
    volumes:
      - shard2_data:/data/db
    ports:
      - "27019:27019"

  mongos:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos
    command: mongos --port 27020 --configdb config_replica_set/configSrv:27017 --bind_ip_all
    ports:
      - "27020:27020"
    depends_on:
      - configSrv
      - shard1
      - shard2

  pymongo_api:
    container_name: pymongo_api
    # Используем образ, указанный в задании. Либо собираем из api_app:
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos:27020"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  config_data:
  shard1_data:
  shard2_data:
